Intermediate step to not to return an URI from HLog#computeFilename().
If we directly return a URI from computeFilename() and we remove the newPath variable, a lot of errors arise to be solved in small steps.

Basically, 2 new methods are created to mimic the behavior of computeFilename() but with a different signature: computeFilenameAsURI(). This method does not uses the dir variable (which is an instance of Path class) and uses instead a new dirUri variable that mimics dir but as a URI. A strange conversion has to be made (see code) and a test in TestLogRolling doesn't pass but I can't see the link.

-------------------------------------------------------------------------------
Test set: org.apache.hadoop.hbase.regionserver.wal.TestLogRolling
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 198.063 sec <<< FAILURE!
testLogRollOnPipelineRestart(org.apache.hadoop.hbase.regionserver.wal.TestLogRolling)  Time elapsed: 63.779 sec  <<< ERROR!
java.io.IOException: Cannot obtain block length for LocatedBlock{BP-2032801527-10.78.37.216-1367604524704:blk_-3953366874379799869_1027; getBlockSize()=1487; corrupt=false; offset=0; locs=[127.0.0.1:58315, 127.0.0.1:58321]}
        at org.apache.hadoop.hdfs.DFSInputStream.readBlockLength(DFSInputStream.java:238)
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:182)
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:124)
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:117)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1130)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:244)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:77)
        at org.apache.hadoop.io.SequenceFile$Reader.openFile(SequenceFile.java:1832)
        at org.apache.hadoop.hbase.regionserver.wal.SequenceFileLogReader$WALReader.openFile(SequenceFileLogReader.java:66)
        at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1752)
        at org.apache.hadoop.io.SequenceFile$Reader.<init>(SequenceFile.java:1773)
        at org.apache.hadoop.hbase.regionserver.wal.SequenceFileLogReader$WALReader.<init>(SequenceFileLogReader.java:58)
        at org.apache.hadoop.hbase.regionserver.wal.SequenceFileLogReader.init(SequenceFileLogReader.java:166)
        at org.apache.hadoop.hbase.regionserver.wal.HLog.getReader(HLog.java:692)
        at org.apache.hadoop.hbase.regionserver.wal.TestLogRolling.testLogRollOnPipelineRestart(TestLogRolling.java:498)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)